name: publish

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  test:
    name: run tests
    runs-on: ubuntu-22.04

    env:
      RUSTFLAGS: "-Cinstrument-coverage -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code"

    steps:
    - name: checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: setup rust
      run: rustc --version

    - name: build
      run: cargo build --verbose

    - name: test
      run: cargo test --release --verbose
      env:
        LLVM_PROFILE_FILE: "target/coverage/test-file.profraw"
        CARGO_INCREMENTAL: "0"

    - name: fetch/run grcov
      run: |
        curl -Lo grcov.bz2 https://github.com/mozilla/grcov/releases/download/v0.8.19/grcov-x86_64-unknown-linux-musl.tar.bz2
        tar xvf grcov.bz2
        rm grcov.bz2

        ./grcov . -s . -t lcov --binary-path ./target/release/ --branch --ignore-not-existing --ignore "./src/tests/*" -o ./target/coverage/tests.lcov

    - name: upload to codecov
      uses: codecov/codecov-action@54bcd8715eee62d40e33596ef5e8f0f48dbbccab # v4.1.0
      with:
        files: target/coverage/*.lcov
        token: ${{ secrets.CODECOV_TOKEN }}

  publish:
    name: publish crate
    runs-on: ubuntu-22.04
    needs: test

    steps:
    - name: checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: setup rust
      run: rustc --version

    - name: build
      run: cargo build --verbose
    - name: build release
      run: cargo build --release --verbose

    - name: dry run publish
      run: cargo publish --dry-run

    - name: upload artifact
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        name: crate
        path: target/package/*.crate

    - name: publish
      run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
